apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsugar-backend-dev
  namespace: default
  labels:
    app: newsugar-backend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsugar-backend
      env: dev
  template:
    metadata:
      labels:
        app: newsugar-backend
        env: dev
    spec:
      containers:
        - name: newsugar-backend
          #AWS Account ID: 0610-3980-4626
          image: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/newsugar-backend:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: newsugar-secrets-dev
                  key: db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: newsugar-secrets-dev
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: newsugar-secrets-dev
                  key: db-password
            - name: NEWS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: newsugar-secrets-dev
                  key: news-api-key
            - name: QUIZ_AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: newsugar-secrets-dev
                  key: quiz-ai-api-key
            - name: REDIS_HOST
              value: "redis-service-dev"
            - name: REDIS_PORT
              value: "6379"
